spring:
  datasource:
    url: jdbc:h2:mem:camunda-db;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: password
    platform: h2

camunda.bpm:
  admin-user:
    id: demo
    password: demo
  filter:
    create: All tasks

camunda:
  bpm:
    generic-properties:
      properties:
        historyTimeToLive: P1D