spring:
  datasource:
    url: jdbc:h2:mem:camunda-db;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    platform: h2
    hikari:
      maximum-pool-size: 10

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  # API CLIENT CONFIG
  cloud:
    openfeign:
      client:
        config:
          quoteApiClient:
            url: http://localhost:8080/

camunda.bpm:
  admin-user:
    id: demo
    password: demo
  filter:
    create: All tasks

camunda:
  bpm:
    generic-properties:
      properties:
        historyTimeToLive: P1D
    deployment-resource-pattern: "classpath:/processes/*.*"
    auto-deployment-enabled: true
    database:
      schema-update: true

# SWAGGER CONFIG
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method
    tagsSorter: alpha
    showExtensions: true
    displayOperationId: true
    displayRequestDuration: true
    deepLinking: true
    defaultModelsExpandDepth: 1

### Spring Boot Actuator ###
# Metrics related configurations
management:
  server:
    port: 8080
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  security:
    enabled: false
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

# LOGS AOP
im:
  aop:
    loggers:
      entering-level: INFO
      entering-message: "Executando o metodo [{method}] com os parametros [{parameters}]"
      exited-level: INFO
      exited-message: "O metodo [{method}] executou normalmente retornando [{return-value}]"
      exited-abnormally-level: ERROR
      exited-abnormally-message: "O metodo [{method}] lancou uma execao [{exception}]"
      elapsed-level: INFO
      elapsed-message: "A execucao do metodo [{method}] durou [{elapsed}]"

# LOGGING CONFIG
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

# ZIPKIN CONFIG

# SEND GRIP EMAIL CONFIG
SENDGRID_API_KEY: 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